spring:
  datasource:
    url: jdbc:p6spy:h2:mem:test
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: test
  sql:
    init:
      #schema必须存在,若只存在data,data中的sql也不会被执行
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always